version: '3.0'
services:
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 8080 -w /config/db.json
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    restart: always
    networks:
      - app_network
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - SAAS_MOCK_URL=http://json-server:8080
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
